CREATE TABLE players(
	player_id integer NOT NULL PRIMARY KEY AUTOINCREMENT,
	player_name TEXT NOT NULL,
	read_ability REAL NOT NULL DEFAULT 0,
	bluff_ability REAL NOT NULL DEFAULT 0,
	paper REAL NOT NULL DEFAULT 0,
	rock REAL NOT NULL DEFAULT 0,
	scissors REAL NOT NULL DEFAULT 0
	wins INT NOT NULL DEFAULT 0,
	losses INT NOT NULL DEFAULT 0
	draws INT NOT NULL DEFAULT 0);
